// Code generated by mockery v2.33.2. DO NOT EDIT.

package apiclientsmocks

import (
	context "context"

	apiclients "github.com/a-novel/go-apis/clients"

	mock "github.com/stretchr/testify/mock"
)

// ForumClient is an autogenerated mock type for the ForumClient type
type ForumClient struct {
	mock.Mock
}

type ForumClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ForumClient) EXPECT() *ForumClient_Expecter {
	return &ForumClient_Expecter{mock: &_m.Mock}
}

// GetImproveRequest provides a mock function with given fields: ctx, query
func (_m *ForumClient) GetImproveRequest(ctx context.Context, query apiclients.GetImproveRequestQuery) (*apiclients.ImproveRequestPreview, error) {
	ret := _m.Called(ctx, query)

	var r0 *apiclients.ImproveRequestPreview
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, apiclients.GetImproveRequestQuery) (*apiclients.ImproveRequestPreview, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, apiclients.GetImproveRequestQuery) *apiclients.ImproveRequestPreview); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiclients.ImproveRequestPreview)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, apiclients.GetImproveRequestQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ForumClient_GetImproveRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImproveRequest'
type ForumClient_GetImproveRequest_Call struct {
	*mock.Call
}

// GetImproveRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - query apiclients.GetImproveRequestQuery
func (_e *ForumClient_Expecter) GetImproveRequest(ctx interface{}, query interface{}) *ForumClient_GetImproveRequest_Call {
	return &ForumClient_GetImproveRequest_Call{Call: _e.mock.On("GetImproveRequest", ctx, query)}
}

func (_c *ForumClient_GetImproveRequest_Call) Run(run func(ctx context.Context, query apiclients.GetImproveRequestQuery)) *ForumClient_GetImproveRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(apiclients.GetImproveRequestQuery))
	})
	return _c
}

func (_c *ForumClient_GetImproveRequest_Call) Return(_a0 *apiclients.ImproveRequestPreview, _a1 error) *ForumClient_GetImproveRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ForumClient_GetImproveRequest_Call) RunAndReturn(run func(context.Context, apiclients.GetImproveRequestQuery) (*apiclients.ImproveRequestPreview, error)) *ForumClient_GetImproveRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetImproveSuggestion provides a mock function with given fields: ctx, query
func (_m *ForumClient) GetImproveSuggestion(ctx context.Context, query apiclients.GetImproveSuggestionQuery) (*apiclients.ImproveSuggestion, error) {
	ret := _m.Called(ctx, query)

	var r0 *apiclients.ImproveSuggestion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, apiclients.GetImproveSuggestionQuery) (*apiclients.ImproveSuggestion, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, apiclients.GetImproveSuggestionQuery) *apiclients.ImproveSuggestion); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiclients.ImproveSuggestion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, apiclients.GetImproveSuggestionQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ForumClient_GetImproveSuggestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImproveSuggestion'
type ForumClient_GetImproveSuggestion_Call struct {
	*mock.Call
}

// GetImproveSuggestion is a helper method to define mock.On call
//   - ctx context.Context
//   - query apiclients.GetImproveSuggestionQuery
func (_e *ForumClient_Expecter) GetImproveSuggestion(ctx interface{}, query interface{}) *ForumClient_GetImproveSuggestion_Call {
	return &ForumClient_GetImproveSuggestion_Call{Call: _e.mock.On("GetImproveSuggestion", ctx, query)}
}

func (_c *ForumClient_GetImproveSuggestion_Call) Run(run func(ctx context.Context, query apiclients.GetImproveSuggestionQuery)) *ForumClient_GetImproveSuggestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(apiclients.GetImproveSuggestionQuery))
	})
	return _c
}

func (_c *ForumClient_GetImproveSuggestion_Call) Return(_a0 *apiclients.ImproveSuggestion, _a1 error) *ForumClient_GetImproveSuggestion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ForumClient_GetImproveSuggestion_Call) RunAndReturn(run func(context.Context, apiclients.GetImproveSuggestionQuery) (*apiclients.ImproveSuggestion, error)) *ForumClient_GetImproveSuggestion_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *ForumClient) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ForumClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type ForumClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ForumClient_Expecter) Ping(ctx interface{}) *ForumClient_Ping_Call {
	return &ForumClient_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *ForumClient_Ping_Call) Run(run func(ctx context.Context)) *ForumClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ForumClient_Ping_Call) Return(_a0 error) *ForumClient_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ForumClient_Ping_Call) RunAndReturn(run func(context.Context) error) *ForumClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// VoteImproveRequest provides a mock function with given fields: ctx, form
func (_m *ForumClient) VoteImproveRequest(ctx context.Context, form apiclients.UpdateImproveRequestVotesForm) error {
	ret := _m.Called(ctx, form)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, apiclients.UpdateImproveRequestVotesForm) error); ok {
		r0 = rf(ctx, form)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ForumClient_VoteImproveRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VoteImproveRequest'
type ForumClient_VoteImproveRequest_Call struct {
	*mock.Call
}

// VoteImproveRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - form apiclients.UpdateImproveRequestVotesForm
func (_e *ForumClient_Expecter) VoteImproveRequest(ctx interface{}, form interface{}) *ForumClient_VoteImproveRequest_Call {
	return &ForumClient_VoteImproveRequest_Call{Call: _e.mock.On("VoteImproveRequest", ctx, form)}
}

func (_c *ForumClient_VoteImproveRequest_Call) Run(run func(ctx context.Context, form apiclients.UpdateImproveRequestVotesForm)) *ForumClient_VoteImproveRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(apiclients.UpdateImproveRequestVotesForm))
	})
	return _c
}

func (_c *ForumClient_VoteImproveRequest_Call) Return(_a0 error) *ForumClient_VoteImproveRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ForumClient_VoteImproveRequest_Call) RunAndReturn(run func(context.Context, apiclients.UpdateImproveRequestVotesForm) error) *ForumClient_VoteImproveRequest_Call {
	_c.Call.Return(run)
	return _c
}

// VoteImproveSuggestion provides a mock function with given fields: ctx, form
func (_m *ForumClient) VoteImproveSuggestion(ctx context.Context, form apiclients.UpdateImproveSuggestionVotesForm) error {
	ret := _m.Called(ctx, form)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, apiclients.UpdateImproveSuggestionVotesForm) error); ok {
		r0 = rf(ctx, form)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ForumClient_VoteImproveSuggestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VoteImproveSuggestion'
type ForumClient_VoteImproveSuggestion_Call struct {
	*mock.Call
}

// VoteImproveSuggestion is a helper method to define mock.On call
//   - ctx context.Context
//   - form apiclients.UpdateImproveSuggestionVotesForm
func (_e *ForumClient_Expecter) VoteImproveSuggestion(ctx interface{}, form interface{}) *ForumClient_VoteImproveSuggestion_Call {
	return &ForumClient_VoteImproveSuggestion_Call{Call: _e.mock.On("VoteImproveSuggestion", ctx, form)}
}

func (_c *ForumClient_VoteImproveSuggestion_Call) Run(run func(ctx context.Context, form apiclients.UpdateImproveSuggestionVotesForm)) *ForumClient_VoteImproveSuggestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(apiclients.UpdateImproveSuggestionVotesForm))
	})
	return _c
}

func (_c *ForumClient_VoteImproveSuggestion_Call) Return(_a0 error) *ForumClient_VoteImproveSuggestion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ForumClient_VoteImproveSuggestion_Call) RunAndReturn(run func(context.Context, apiclients.UpdateImproveSuggestionVotesForm) error) *ForumClient_VoteImproveSuggestion_Call {
	_c.Call.Return(run)
	return _c
}

// NewForumClient creates a new instance of ForumClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewForumClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ForumClient {
	mock := &ForumClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
